### PR TITLE
Updating version number in installation docs

### PR DESCRIPTION
**Pull request by lewisdenny**
Updating version number in installation docs, this being incorrectly set prevents hugo serve from running and causes an error to be served.

### CODE REVIEW

**Comment by khusika** [comment]
> Updating version number in installation docs, this being incorrectly......

I do agree with the typo in the post documentation, can you also do both for [france translation](https://github.com/khusika/FeelIt/blame/main/exampleSite/content/posts/theme-documentation-basics/index.fr.md#L97) and [chinese translation](https://github.com/khusika/FeelIt/blame/main/exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md#L95)?

> ......set prevents hugo serve from running and causes an error to be served.

About this statement, is this just to emphasize "_the prevention_" or are you really getting an error with the `start-production` rules which is defined in [_Getting Started Guide_](https://github.com/khusika/FeelIt#getting-started).

**Comment by lewisdenny** [comment]
>I do agree with the typo in the post documentation, can you also do both for france translation and chinese translation?

Done

Yes, it throws the following error when the version is set incorrectly:
~~~
ERROR 2021/07/09 12:36:42 Compatibility Error 兼容性错误

0.2.X -> 1.0.X:
You have an incompatible update. See https://github.com/khusika/FeelIt/releases
你进行了一次不兼容的更新. 参考 https://github.com/khusika/FeelIt/releases
WARN 2021/07/09 12:36:42 

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.
ERROR 2021/07/09 12:36:42 logged 1 error(s)
~~~

**Comment by khusika** [comment]
> Done

Squash your commit please
`git reset --soft HEAD~3 && git commit --amend`

**Comment by khusika** [comment]
Closed as of this 3b90474038c37f7ba33652432398a2795699c70f

**Pull request closed without merging**
